version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: tk3c_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: zxcvbnm+1013
      MYSQL_DATABASE: tk3c_price_tracker
      MYSQL_USER: tk3c_user
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
